name: CI
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [macOS-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
        node-version: [10, 12, 13]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm i
      - name: Start Redis
        run: docker run -d -p 6379:6379 --rm redis:5.0.7
      - name: Start Redis Cluster
        uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 30001
          master2-port: 30002
          master3-port: 30003
          slave1-port: 30004
          slave2-port: 30005
          slave3-port: 30006
      - name: Tests
        run: npm run test
