name: CI
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        node-version: [10, 11, 12, 13]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm i
      - name: Start redis
        run: docker run -d -p 6379:6379 --rm redis:5.0.7
      - name: Tests
        run: npm run test
